language: node_js
node_js:
  - '8'
  - '9'  
  - '10'
notifications:
  email: false
script: npm run cover
after_success: cat /home/travis/build/ichiriac/ejs2/coverage/lcov.info | /home/travis/build/ichiriac/ejs2/node_modules/coveralls/bin/coveralls.js